### ISSUE TITLE
chocolatey works great, but Chocolatey GUI stopped working (never has worked for me) 

### ISSUE THREAD

**Issue by rbme33** [chocolatey/ChocolateyGUI#176]
Description:
  Stopped working

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: chocolateygui.exe
  Problem Signature 02: 0.11.4.2
  Problem Signature 03: 5418969a
  Problem Signature 04: Anonymously Hosted DynamicMethods Assembly
  Problem Signature 05: 0.0.0.0
  Problem Signature 06: 0
  Problem Signature 07: 0
  Problem Signature 08: ffffffff
  Problem Signature 09: StructureMap.StructureMap
  OS Version:   6.0.6002.2.2.0.768.3
  Locale ID:    1033

Read our privacy statement:
  http://go.microsoft.com/fwlink/?linkid=50163&clcid=0x0409

**Comment by Rabupi** [comment]
This might be a bit late and I don't know if it has been resolved but I recently had the same issue...
Going back and forth installing / uninstalling the normal and -pre. Turns out that there was a problem with the DB in "C:\Users\%USER%\AppData\Local\Chocolatey GUI\" and I also had a "Chocolatey GUI" and a "ChocolateyGUI" in "C:\Users\%USER%\AppData\Roaming\Chocolatey GUI\" so I killed any and all "ChocolateyGui.exe" processes then deleted all the "Chocolatey GUI" and "ChocolateyGUI" folders in "Local" and "Roaming" and opened Chocolatey GUI again and !! TADA !! all working again.
I hope this helps anyone who still experience this issue.
