### ISSUE TITLE
Review MSI package

### ISSUE THREAD

**Issue by gep13** [chocolatey/ChocolateyGUI#209]
@DarwinCSIWindowscom based on your knowledge that you showed here:

https://github.com/chocolatey/choco/issues/50

You seem like the right guy to talk to about MSI's.

Would you be willing to do a review of the WiX package that is used by ChocolateyGUI?  Are we doing things that aren't "right"?

Thanks!

Gary

**Comment by RichiCoder1** [comment]
:+1:

**Comment by DarwinCSIWindowscom** [comment]
Sure I can do that.

One question - do you intend that the Chocolately MSI install "over top" of an existing version (get all the MSI details *perfect* from release to release) or uninstall the old version?  

Given the small size of Chocolatey I don't see a significant upside to supporting "install over" with the possible exception of handling upgrading "yourself" via file renames on reboot.

To be clear, my original comments were actually more to how Chocolatey handles all the MSIs that it processes for packages - so the dividends in following the upgrade recommendations in the referenced thread are potentially huge :) because I think you'll run into more and more conflicts as people try to use Chocolatey to upgrade existing software (whether installed by Chocolatey or not).

**Comment by gep13** [comment]
Yip, I totally understand the comments in the other thread.  It was based on that conversation though that I wanted to make sure that ChocolateyGUI has it's own house in order :-)

I literally put the WiX package together based on some snippets that I found on the interwebs, with no "real" understanding about how all the pieces fit together.  And that is where I was hoping that you might be able to come in.

I think the best approach, based on my understanding, would be to support uninstalling first, and then installing the new version.  There is a config file associated with ChocolateyGUI, which we would like to preserve across installs/upgrades, but that would be the only thing that I can think would be impacted.

Thanks for your help!

**Comment by gep13** [comment]
Having ChocolateyGUI be able to do self updating, would be a nice touch, but given that we can use Chocolatey itself to handle the updates, I don't think that this functionality would be required.

**Comment by RichiCoder1** [comment]
Another nice to have would be someway of detecting an existing Chocolatey or Chocolatey vNext installation. There's been more than once were we've had people install ChocolateyGUI and be suprised it doesn't work without an existing chocolatey setup.

**Comment by DarwinCSIWindowscom** [comment]
Ok some comments:

**Requiring Chocolatey**
To require chocolatey before install, just add this to the LaunchConditions table:
Condition: %CHOCOLATEY
Description: You must install chocolatey before you can install the GUI.  See http://whatever.
**DONT ADD A TRAILING PERCENT**

That condition is evaluated as "<If> %CHOCOLATEYINSTALL% 
<contains *anything at all*> then <this launch condition is statisfied> otherwise <display the description>

The only time it wouldn't work is is Chocolatey had been installed in the same command line process as your package is attempted - but if people follow your instructions to set the environment variable in the process - it would still work.  Actually it would be really nice if the base chocolatey install was smart enough to set the variable in the current process as well.

**Remove Uninstall Shortcut in Start Menu**
Even with EXE installers you're not supposed to this - but especially when the install framework supports uninstalls native.

**Possibly Remove MsiFileHash Table**
This table is for causing self-healing of non-versioned files.  So if a self-heal occurs, these will revert.  That might be ok for your *.exe.config if it does not change - but sources.xml seems like will be edited by customers.

**Possible Remove Registry Table?**
There just seems to be one registry key indicating whether a shortcut was created.  Is it referenced by anything?

**For User Config, DO NOT include the file in the MSI**
The *old* method of having your EXE create a default configuration file on first startup is still valid and in this case very useful.  If your software creates this - it is not in the MSI.  It will never be self-healed over, or removed.  If you don't want MSI to manage a file - don't let it be aware of it.

**MSI does not self-update**
MSI has never had a self-update from the internet functionality built in.

**Do not use .NET .config file for storing user changable settings**
Your users *SHOULD* be using UAC.  When you put settings into application.exe.config and then *also* put that file in Program Files - then regular users can't change it without elevating.
If the file is supposed be *changable by users*, but "per-machine config*, then it goes in %PROGRAMDATA%\ChocolateyGUI\datafile.  (Use %ALLUSERSPROFILE% instead of %PROGRAMDATA% for compat with XP - and win7 and later).  For per-user, %APPDATA%\ChocolateyGUI\datafile for roaming profile (goes with user to different machines in corporate environemnt) and %LOCALAPPDATA%\ChocolateyGUI\datafile for a given machine only.
If you create this file on startup - it will automatically be preserved between full uninstalls and reinstalls.
I'm not sure it would happen, but if someone installs ChocolateyGUI on RDS / Citrix - then using a .config in program files is even worse.

**Major Upgrades**
Your upgrade table looks good and the placement of RemoveExistingProducts means a full de-install before install.  However, for your package to trigger a major upgrade every time you might need to change the product code every time.  You *might* also need to change the *major* version every time - but I'm not 100% sure.  If you've been getting a major upgrade without doing those things, then the upgrade table match may be over riding the other two.

You could also handle the deinstall of the old version in ChocolateyInstall.ps1 in your chocolate nuget package - but doing it in the MSI means it would work whether or not using chocolatey to install.

**Comment by gep13** [comment]
> @RichiCoder1 said
Another nice to have would be someway of detecting an existing Chocolatey or Chocolatey vNext installation. There's been more than once were we've had people install ChocolateyGUI and be suprised it doesn't work without an existing chocolatey setup.

This is related to this issue: https://github.com/chocolatey/ChocolateyGUI/issues/206

**Comment by gep13** [comment]
Also related to this request:

https://github.com/chocolatey/ChocolateyGUI/issues/115

**Comment by RichiCoder1** [comment]
Address a number of these issues in 6108d42.

Mainly:
- Killed off app subfolder and uninstaller shortcut in program menu
- Removed registry key. Was indeed pointless and an ICE validation error workaround.
- User settings are now stored independent of installation.
- Scan for `%ChocolateyInstall` existence, and fail if not present. At some point, I may build out a bootstrap to handle installation if it's missing.

**Comment by RichiCoder1** [comment]
Pretty happy with our MSI now.
