### ISSUE TITLE
Refreshing package list ignores search query/options

### ISSUE THREAD

**Issue by twpol** [chocolatey/ChocolateyGUI#264]
If I have a search query filled in or have selected the "Show Only Packages with Updates" option, when I hit "refresh packages" it shows me all of the packages instead of those matching the query or those with updates.

**Comment by gep13** [comment]
@twpol Hmmm, I am not sure I would expect that the filters remain after a refresh of the packages.  Should we simply clear/reset the search options when the refresh button is pressed?

**Comment by twpol** [comment]
In my particular case, I was updating packages with the `choco` command and checking what still needed to be update with ChocolateyGUI, so I did want the filter to still apply. :)

Either way will bring the UI back to being self-consistent, but I do also think leaving the filters is the path of least surprise.

**Comment by strigona-worksight** [comment]
The current flow definitely feels weird... 

Filter to "Show Only Packages with Updates"
(List is now filtered)
Right click on package > Update
(Package update is installed)
(List is no longer filtered - has not been refreshed as it still displays old version numbers)

You then have to uncheck "Show Only Packages with Updates", then recheck it. If you want to update the list, make sure to do that first, otherwise you'll have to uncheck/recheck yet again.

**Comment by DIDoS** [comment]
I agree with @strigona-worksight either the checkbox is automatically unchecked afterwards or the list is filtered. The checkbox definitely indicates a wrong status.

**Comment by RichiCoder1** [comment]
I realize this is the original issue, but I'm closing as duplicate to #309. Will try and get this resolved ASAP!
