### ISSUE TITLE
Problems installing ChocolateyGUI on Windows 10

### ISSUE THREAD

**Issue by ustcltx** [chocolatey/ChocolateyGUI#300]
![choco](https://cloud.githubusercontent.com/assets/6998333/12255114/49b8aa1e-b92b-11e5-9532-a841145c6ffd.png)

 I think I have installed powershell in my Windows 10.

**Comment by gep13** [comment]
@ustcltx  Hmm, I see what the problem is.

Since you are using our MyGet Feed, it is looking for the PowerShell package at that same location, and the PowerShell package isn't mirrored onto that feed.  Now, although you already have PowerShell installed, Chocolatey itself doesn't know about it.

Do that following:

`choco install powershell -y`

which should attempt the PowerShell installation, taking the package from the Chocolatey.org feed.  This shouldn't actually install anything, but it will let Chocolatey know that PowerShell is installed.

Then run the installation command for ChocolateyGUI again.

Let us know how you get on.

**Comment by ustcltx** [comment]
it is really works! Thanks for your help!

**Comment by gep13** [comment]
Glad to hear it! :+1:
