### ISSUE TITLE
Execution Level - Prefer highestAvailable over requireAdministrator

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#342]
@RichiCoder1 @gep13 any reason that the app.manifest is set to `requireAdministrator` over `highestAvailable`?

https://github.com/chocolatey/ChocolateyGUI/blob/97eee257de524a841dc4f27b1ce22fce4acfe223/Source/ChocolateyGui/app.manifest#L7

Asking because I would prefer it to be highestAvailable and I don't yet have a full understanding of all of the nuances that may be associated with that.

**Comment by RichiCoder1** [comment]
Unfortunately there was a good reason. Performing any operation besides `list` (and previously, even list) requires privileged access to ProgramData\Chocolatey to even start doing anything, and even then packages require elevation to preform operations. So we avoided the whole shebang by simply elevating by default.

I would, however, love to fix this. One option, since listing no longer requires ProgramData write access, would be to move ChocoGUI back to non-admin by default and simply force elevation when performing "privileged" actions.

**Comment by RichiCoder1** [comment]
Closed by 6698de25. ChocolateyGUI (and it's subprocess) now match the user's elevation by default and the subprocess elevates as necessary.

**Comment by ferventcoder** [comment]
Superseded by #465
