### ISSUE TITLE
ChocolateyGUI errors on subprocess when attempting to open more than one instance of ChocolateyGUI

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#372]
This happens when opening the GUI as a non-admin

![image](https://cloud.githubusercontent.com/assets/63502/21814770/04fb834c-d720-11e6-9765-de7951837a13.png)

**Comment by gep13** [comment]
@RichiCoder1 can you do a brain dump here about what the subprocess is, and what problem it is solving?  Thanks!

**Comment by RichiCoder1** [comment]
Well that's an odd error.

ChocolateyGUI.Subprocess is an independent child process of ChocolateyGui that acts as an out-of-process shim for the Chocolatey API. It allows for crash isolation and recovery as well as, most importantly, independent elevation of the ChocolateyGui.Suprocess so that admin operations may be requested and performed without requiring a full application restart.

ChocolateyGui.Subprocess is automatically spun up when the first ChocolateyApi request is made (usually sources), and functions by starting the Subprocess (with the appropriate port to listen on), and then waiting for the Subprocess to set a waithandle. Once that happens, a [Web Socket RPC](https://github.com/Code-Sharp/WampSharp) is opened, and all Chocolatey API calls are made as normal.

@ferventcoder Do you a `%ProgramData%\ChocolateyGUI\ChocolateyGui.Subprocess.[Date].log` available? Is this happening every time you start the application, or was this a one time incident?

**Comment by ferventcoder** [comment]
Found it
It's multiple ChocolateyGUI's open.

**Comment by ferventcoder** [comment]
Sorry, I wasn't paying attention to which log file.

![image](https://cloud.githubusercontent.com/assets/63502/21815806/8a2fa87e-d723-11e6-953c-2203ec8fd0dd.png)

**Comment by RichiCoder1** [comment]
Well nuts. One thing I never implemented was socket-in-use checking, every instance of ChocolateyGUI will try and use the same socket xD. I'll work on fixing that.

**Comment by ferventcoder** [comment]
Once I shut down the one from the admin user, then boom, it works great!

**Comment by gep13** [comment]
@RichiCoder1 @ferventcoder do we think that it would make sense to make ChocolateyGUI a single instance application?

**Comment by RichiCoder1** [comment]
Then we'd have to fight w/ process elevation again amongst other things. The OOP actually works really well, I just need to fix the socket picking. @gep13 Any particular reason you'd like to move back?

**Comment by RichiCoder1** [comment]
Closed by #407
