### ISSUE TITLE
Release notes in about dialog empty

### ISSUE THREAD

**Issue by pascalberger** [chocolatey/ChocolateyGUI#499]
The release notes in the about dialog of the released 0.15 version still reads:

```
This file will be updated as part of the Chocolatey GUI build process.

If you want to see the current release notes, please check here
```

Seems like the updating of the file during the build process doesn't work

**Comment by gep13** [comment]
@pascalberger dang it!

No, that part is working, I specifically checked that with @RichiCoder1 when we tagged the branch.

The problem here is that @ferventcoder then built the project again in order to sign the application, as a result, the release notes were not pulled into the build that shipped with 0.15.0.

We are going to need to figure this out for the next release.

Thanks for raising this!

**Comment by ferventcoder** [comment]
I missed a step then...

**Comment by gep13** [comment]
@ferventcoder no, I wouldn't say that.  Rather, Cake.Recipe is built on a few assumptions, namely that the final push/build is happening on a CI system, however, this isn't happening here.  I made some assumptions when switching Chocolatey GUI build to not do some steps, and I forgot about this one.
