### ISSUE TITLE
On Load of any source, outdated is running (logging) every time

### ISSUE THREAD

**Issue by ferventcoder** [chocolatey/ChocolateyGUI#525]
Not sure if anyone else is seeing this as well. Outdated appears to be in the logs when switching between sources.

**Comment by RichiCoder1** [comment]
That sounds about right, especially now that we check for outdated packages in remote views too. Will need to do a better job of caching results.

**Comment by ferventcoder** [comment]
At least cache for a few minutes.

**Comment by gep13** [comment]
In implementing this, a few changes have been made.

Settings screen has been broken out into two separate tabs, one for Chocolatey GUI and one for Chocolatey:

![image](https://user-images.githubusercontent.com/1271146/57125586-e4e60780-6d81-11e9-958f-0ab21ca8d062.png)

![image](https://user-images.githubusercontent.com/1271146/57125602-f3342380-6d81-11e9-90c6-47313ba66603.png)

Now, functionality in terms of how Features and Settings are handled are common between Chocolatey GUI and Chocolatey.

CLI functionality has been extended to include the ability to set Config values through the CLI:

![image](https://user-images.githubusercontent.com/1271146/57125680-2bd3fd00-6d82-11e9-829a-9995f9caebc1.png)

![image](https://user-images.githubusercontent.com/1271146/57125701-3b534600-6d82-11e9-83f9-87d48e412ebd.png)

![image](https://user-images.githubusercontent.com/1271146/57125717-49a16200-6d82-11e9-80a3-02e2bc7d87c2.png)

![image](https://user-images.githubusercontent.com/1271146/57125737-57ef7e00-6d82-11e9-9191-f33998ede564.png)

All of the above output is localized, and once merged can be translated via Transifex, so any help in this area (@mwallner @pascalberger @AdmiringWorm @punker76) would be gratefully appreciated.

**Comment by gep13** [comment]
Here are some screenshots of the above working in Dutch :-)  @ferventcoder thought you might be interested in seeing these.

![image](https://user-images.githubusercontent.com/1271146/57174960-394ebd00-6e3e-11e9-9306-25a63e80bda7.png)

![image](https://user-images.githubusercontent.com/1271146/57174966-45d31580-6e3e-11e9-8bcc-b91b32b45cd5.png)

![image](https://user-images.githubusercontent.com/1271146/57174971-508daa80-6e3e-11e9-9b79-9a4d7eccb899.png)

Thanks @mkevenaar for creating the screenshots!

**Comment by gep13** [comment]
@ferventcoder if you notice in @mkevenaar screenshots, he is making use of the shim that is created during installation.  This has a side effect of returning to the console prompt before the result from Chocolatey GUI.  This is due to this:

https://github.com/chocolatey/ChocolateyGUI/commit/6370e5a4a30928dbe520ae5b5373ed19b16e435f

Would love some input on whether this can be improved.  Thanks

**Comment by mkevenaar** [comment]
@gep13 the `cup`, `cinst` e.a. (shim?) executables are not showing this behavior. I think it might be that in this case shimgen is creating a GUI shim, as it should it; it's a GUI package. I believe a gui shim should exit once the actual software is started.

**Comment by gep13** [comment]
@mkevenaar the “issue” here is that chocolateygui.exe is both a CLI and a GUI application. If it is ran with arguments, it invokes the CLI, otherwise the GUI. As a result, the shim has to be created as either one, or the other, not both.

If the shim is changed, invoking from the CLI with arguments will work as you might expect. However, when invoked with no arguments the GUI would open, but the command prompt would be blocked until the GUI is closed, which is also not ideal.

I chose what I thought was the lesser of the two evils. But this can certainly be changed if required.

**Comment by gep13** [comment]
I don’t know if the shim is clever enough to know that it should default to CLI sim when invoked with arguments, and GUI shim when not. That would be the ideal situation here.
