### ISSUE TITLE
Chocolatey GUI pulls download stats only from the community feed 

### ISSUE THREAD

**Issue by bcurran3** [chocolatey/ChocolateyGUI#564]
(or maybe only from the first source feed)

I have a local Chocolatey Simple Server (CSS) with just a few packages on it. All but one of those packages are also in the Chocolatey community repository.

When I first click to see the feed on my CSS, all package download stats display as "-1"

When I double click a package to view details and Chocolatey GUI pops up the white and blue loading..., the download stats from the community feed display, not my local CSS feed. i.e. a package that has been installed less than 10x from my local CSS shows 864 total downloads.

A reverse example of this is the chocolatey.licensed feed. Even though chocolatey.extension is installed, download status show 0 and 0. (This package, of course, isn't in the community feed.)

I'm assuming the stats should show from the download counters at the chosen source and not default to the community feed.

**Comment by RichiCoder1** [comment]
I'm pretty sure we're not doing any special here. Does CSS produce stats by default @ferventcoder @gep13 ?

**Comment by bcurran3** [comment]
@RichiCoder1 If download statistics aren't part of the simple server feed, CGUI should display something letting the user know that the statistics are unknown instead of pulling and displaying statistics from a completely different source.

**Comment by TheVakman** [comment]
@ferventcoder @RichiCoder1 We don't keep the community feed enabled here so ours always show -1. I'm also pretty sure that Chocolatey Simple Server doesn't offer statistics. Although, there could have been something that I missed. It would be nice if that was the case but there are other options that have statistics should I require them.

With that said, if statistics aren't available for a source, ChocolateyGUI should either hide this text or at least (and what might be easier to do) is to display 0 instead of -1.

From a user perspective as users will go in for Self Service packages, -1 is a strange thing for them to see and leads to questions when they using ChocolateyGUI.
