### ISSUE TITLE
nuspec - Add .NET Framework 4.x Dependency

### ISSUE THREAD

**Issue by FranklinYu** [chocolatey/ChocolateyGUI#632]
The description says

> This package will only work correctly on Windows 7 SP1 through Windows 10 (1708) or Windows Server 2008 R2 SP1 through Windows Server 2016, and requires *.NET Framework 4.5.2* at minimum.

I hereby propose to add [`DotNet4.5.2`](https://chocolatey.org/packages/DotNet4.5.2) to dependency list. #40 is related, but that is about .NET 4.0.

Moved from [Disqus comment](https://chocolatey.org/packages/ChocolateyGUI#comment-4234298910).

**Comment by ferventcoder** [comment]
I'm proposing https://chocolatey.org/packages/dotnetfx/4.5.2.0 instead. 

~~~xml
<dependency id="dotnetfx" version="4.5.2.0" />
~~~

Take a minimum version dependency on .NET Framework package that @jberezanski has set up.

**Comment by ferventcoder** [comment]
The only thing I don't like here is that if someone does NOT want to upgrade to a newer .NET framework dependency, this will do so. Perhaps a second set of packages that are specific to ensuring a minimum version or no-opping.

**Comment by ferventcoder** [comment]
@jberezanski This goes back to why I said a single .NET Framework package needs more discussion.  I want to specify a minimum version dependency and NOOP if it is met. That is not possible with what has been done with the dotnetfx package because by design `<dependency id="dotnetfx" version="4.5.2.0" />` means at least this version, but install the latest one available as long as there are no other constraints. So today if I ran this, it would install `4.7.2.20180712`. I may not want to go that high on .NET Framework due to other constraints. 

However, it's not as simple as saying I can specify an exact version dependency on the dotnetfx package either. I potentially block other valid and compatible installations If I add it like this: `version="[4.5.2.0]"` (exact version):

* If we already installed something else that had a higher minimum, it would fail this install
* If we try to install something else after this took a higher minimum, it would fail that installation

Really the best route is to mix what you have done with 

~~~powershell
$release = 379893
$version = '4.5.2'
$productNameWithVersion = "Microsoft .NET Framework $version"
$url = 'https://download.microsoft.com/download/E/2/1/E21644B5-2DF2-47C2-91BD-63C560427900/NDP452-KB2901907-x86-x64-AllOS-ENU.exe'
$checksum = '6C2C589132E830A185C5F40F82042BEE3022E721A216680BD9B3995BA86F3781'
$checksumType = 'sha256'
 
if (Test-Installed -Release $release) {
    Write-Host "$productNameWithVersion or later is already installed."
    return
}
~~~

Into several packages that are a bit more official. And add a package parameter that would allow someone to force that particular version to be installed, even if there is a newer version. That way you get the best of both worlds.

Thoughts?

**Comment by ferventcoder** [comment]
I should say the constraints are felt most often by organizations and not necessarily individuals. We have both types of users on the community repo.

**Comment by ferventcoder** [comment]
I should note for other folks who find there way here, I did not raise an issue at https://github.com/jberezanski/ChocolateyPackages/issues because by design there isn't any change to the dotnetfx package I can suggest at the moment. It's a partial solution - it meets the case where folks are fine with getting the latest .NET version when they install something.

**Comment by gep13** [comment]
@FranklinYu I have added the suggested dependency.  This currently fails installation during package installation on the local test environment do to dependency requiring a reboot, so an exemption will be required for moderation process.

This may require some changes based on some potential work/changes to dotnet packages on chocolatey.org, but that can be revisited at a later date.
