### ISSUE TITLE
Add a dark mode

### ISSUE THREAD

**Issue by Vresod** [chocolatey/ChocolateyGUI#685]
This could be put into the settings panel.

**Comment by gep13** [comment]
@Vresod this is an interesting idea.  This isn't something that I would be able to take on, as I am not a designer, so this would need some outside help in order for it to progress.

**Comment by lucknaumann** [comment]
Even though you're not a designer, dark themes don't need to be difficult. If you want an idea go to DuckDuckGo search engine https://duckduckgo.com/ Settings - Themes and choose Dark or Terminal. The BG is simply a medium to dark gray and the text white to light gray. The Terminal version shows some colors for text (clicked and unclicked links, URLs, etc.). To see other colors used for certain searches:  https://duckduckgo.com/?q=youtube-dl+how+to+download+audio+separate+youtube&t=ffab&ia=web&iax=qa

I used a web page since it's not a program you need to install or download but the same principals apply. 

I did some screenshots just as an example. I basically just inverted the colors, which is really just the main principal of dark themes. White backgrounds to black or dark to medium gray and dark text would become white or light gray. While there could be colors (such as blue) there really doesn't have to be. It's a simple program so a simple grayscale theme would be fine. Don't forget the Settings pages and text boxes as well. =]

I hope this helps. 

![ChocoInterface-Gray](https://user-images.githubusercontent.com/51302763/64579848-2d698f00-d339-11e9-8ba5-8f899d6f9dd3.PNG)
![ChocoLoading-Dark](https://user-images.githubusercontent.com/51302763/64579855-335f7000-d339-11e9-86d8-267bb969d3f4.png)
![ChocoInterface-BLK](https://user-images.githubusercontent.com/51302763/64579552-268e4c80-d338-11e9-9210-26b791c26324.png)

**Comment by punker76** [comment]
@gep13 @lucknaumann MahApps provides also a dark theme, so it should be easy to convert the existing "light" theme to a dark theme.

**Comment by lucknaumann** [comment]
@punker76 Sounds great!

**Comment by JustWhelmed** [comment]
Really hope this gets implemented. Every app should have a dark theme, it's just so much easier on the eyes.

**Comment by lucknaumann** [comment]
Hey, I just wanted to check-in and see how things were progressing. Any update on ETA for a dark theme? Thanks!

**Comment by JesFEREM** [comment]
bump. 
Yeah dark mode should be as easy as turning the background black and the text white. That's what i recommend because MS literally does that

**Comment by AdmiringWorm** [comment]
@JesFEREM unfortunately it is almost never as easy as that.

Creating a dark theme (even just changing the background to black and the text to white) requires implementing a completely new style, updating the already used colors for different controls (background, foreground, border, etc) and make sure they don't clash with anything else.

Implementing the ability to actually select the wanted style would also be needed.

**Comment by gregkolodny** [comment]
@punker76 is this triaged?

**Comment by punker76** [comment]
@gregkolodny 

> @punker76 is this triaged?

it’s on my todo list and will come soon
