### ISSUE TITLE
Add configuration parameter to specify which source should be defaulted to when application loads

### ISSUE THREAD

**Issue by adilio** [chocolatey/ChocolateyGUI#808]
Hi @gep13! Firstly, let me say the work you're doing here is great, and I LOVE using ChocolateyGUI 😁 . I may be biased.

It would be _very_ useful for admins to be able to control which source gets defaulted to when ChocolateyGUI first opens. Something like a "preferredsource" parameter?

Whether this is a C4B-only feature or OSS one, is entirely up to you. Admins have told us numerous times that their end-users aren't always aware enough to know which source to go to by default, as there are often multiple sources. Even if there was some logic to see which source is enabled for self-service, and use that as default, that could work as well.

**Comment by gep13** [comment]
@adilio thank you for raising this.  I had a chat with @ferventcoder and we decided that this would be a Business Customer feature, which would require an update to the Chocolatey GUI Licensed Extension in order to light up this feature.

Related issue was created here: https://github.com/chocolatey/chocolatey-licensed-issues/issues/198

**Comment by gep13** [comment]
**NOTE:** While this feature toggle will exist within the OSS version of Chocolatey GUI, it will not be used, and this feature will only be acted on by the Chocolatey GUI Licensed Extension.

**Comment by gep13** [comment]
Re-opening this, as there will be some work to make it possible to override this functionality in the Chocolatey GUI Licensed Extension.
