### ISSUE TITLE
allow multiple item selection using checkboxes in corner of software icons

### ISSUE THREAD

**Issue by demdante** [chocolatey/ChocolateyGUI#824]
Hello.  Let me start by saying I am really liking the current gui layout of the chocolatey GUI.  Very nice!!!  As I was marveling about chocolatey GUI's upgrade from a simple list to the visually appealing icon list that it has become and started to update the many out-of-date chocolatey packages installed on my system, I found myself looking for a checkbox in the top left hand corner of the icon box to allow users to select multiple items without holding down "CTRL" on the keyboard, kind of like how you would in windows explorer:

![pic](https://user-images.githubusercontent.com/64720591/111080131-f6a7a280-84f4-11eb-8ec1-b098b56b1ab6.png)

I did not find this feature, unfortunately, and I think its inclusion in the next release of chocolatey gui would really improve the application's usability for users.

**Comment by umarabdullahmansoori** [comment]
Yes, These 2 features should be added in GUI
1. Allow multiple Packages installing
2. Login and syncing packages in account (in GUI) , So in case of windows reinstall, we can directly install all packages

**Comment by gep13** [comment]
@demdante There is already an open issue for installing multiple packages at once:

https://github.com/chocolatey/ChocolateyGUI/issues/12

@umarabdullahmansoori your request I believe is covered in this issue.

Rather than creating duplicate issues, it is best to add to existing issues with other suggestions/ideas.  Can I ask that you both do this.

For now, I am closing to close out this issue as a duplicate.
