### ISSUE TITLE
How to change install location for packages?

### ISSUE THREAD

**Issue by FiftyFour7250** [chocolatey/ChocolateyGUI#863]
Hey. I'm new to Chocolatey, could you tell me please how to change the installation location of programs? For now everything is installing in C:\ I would like to change the installation path to D:\ChocolateyPrograms\

**Comment by Toadfield** [comment]
I have a similar problem,Chocolatey installs most programs to the program files or program files (x86),but I want that it installs it to a different folder cause Program Files needs admin priviligis.

**Comment by gep13** [comment]
@FiftyFour7250 In the commercial versions of Chocolatey, there is a feature that attempts to provide the functionality of allowing installation to a single global location:

https://docs.chocolatey.org/en-us/features/install-directory-override

However, in the absence of this feature, it is still possible to pass install arguments during the `choco install` command which are passed through to the native installer, to allow control of installation location.  In order to use this though, you need to know ahead of time, likely via the vendor website for the application, the installation arguments that need to be passed in.

Passing installation arguments via Chocolatey GUI isn't currently possible, but this is something that is being worked on, and should be in the next release.

**Comment by Toadfield** [comment]
@gep13 So if I got it right then with the commercial version of chocolatey I just have to run a command once that specifies where packages get installed and then it works for every application in the future and I don't have to do any extra command after that to install programs to this location?
