### ISSUE TITLE
[Feature Request] Being able to specify where all packages get installed

### ISSUE THREAD

**Issue by Toadfield** [chocolatey/ChocolateyGUI#867]
It is so dumb that all the packages get installed in program files or program files (x86) cause many programs need admin priviliges then which they normally don't need.
I just want to be able to set that every package gets installed somewhere else instead.

**Comment by ryanrichter94** [comment]
@Toadfield You've asked this question in multiple GitHub repos and multiple times in those repos. Doing this repeatedly will get you banned from the chocolatey repos. I'd recommend referencing the documentation for chocolatey on https://docs.chocolatey.org. I'd also implore you to read the Readme for this project, specially the part that asks you to raise questions in our [Gitter chat room](https://gitter.im/chocolatey/choco) instead of opening multiple issues in GitHub.
