### ISSUE TITLE
Installation path

### ISSUE THREAD

**Issue by xmha97** [chocolatey/ChocolateyGUI#949]
Hi,
ChocolateyGUI is a 64bit app.

![image](https://user-images.githubusercontent.com/23485114/177080665-dd4c29f7-6a01-4d73-bae6-5ddd86cbb634.png)

It should install on `C:\Program Files` not `C:\Program Files (x86)`

![image](https://user-images.githubusercontent.com/23485114/177080746-d2f5959b-eed7-4641-b0ad-fcb264f9d9fa.png)

Thanks.

**Comment by corbob** [comment]
Thanks for the report! I have done a bit of digging, and I am thoroughly convinced that Windows 10 at least does not report the architecture properly in Task Manager. Of interest, I installed Process Explorer and SigCheck from SysInternals and checked the ChocolateyGui.exe. SigCheck reports it's 32-bit, and Process Explorer says it's 64-bit:

<img width="925" alt="image" src="https://user-images.githubusercontent.com/30301021/193320116-7fe38d80-7c1d-4288-af55-c6a6d27ae099.png">


For now, since we are a 32-bit application installing to the 32-bit Program Files, I'm going to close this, if this changes we can reopen or open a new issue in the future.
